version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./DockerFile-Dev
    container_name: node-server
    volumes: 
        - .:/home/app/:rw
    working_dir: /home/app
    ports:
        - "80:80"